# Generated by Django 2.2.2 on 2019-07-07 01:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=60)),
                ('cedula', models.CharField(help_text='Ejemplo: V011223318', max_length=11, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Cedula ingresada incorrectamente, ingresarla nuevamente', regex='^[V|E]{1}[0]{1}[0-9]{7,9}$')])),
                ('fecha_nac', models.DateField(help_text='Año-Mes-Dia, Ej.: 2019-07-03', verbose_name='Fecha de nacimiento')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('telefono', models.CharField(help_text='Ejemplo: 02742245565', max_length=11)),
                ('direccion', models.CharField(max_length=150)),
            ],
        ),
    ]
